{% set name = "napari-tomocube-data-viewer" %}
{% set version = "2024.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tomocube-data-viewer-{{ version }}.tar.gz
  sha256: 5e417b0c78fbb71529088afb9f06a3a84867d6ba70602a3e9e04790f8c6f48f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - tcfile <=2023.7

test:
  imports:
    - napari_tomocube_data_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-tomocube-data-viewer
  summary: A plugin to visualize three-dimensional data from Tomocube's microscopy
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ehgus/napari-tomocube-data-viewer

extra:
  recipe-maintainers:
    - ehgus
    - goanpeca
    - jaimergp
