{% set name = "napari-tomocube-data-viewer" %}
{% set version = "2023.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tomocube-data-viewer-{{ version }}.tar.gz
  sha256: 2254acc09df6c2714d9130e89c9ff597323c5f3ab6110b6655b2b8d88281e1ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - tcfile

test:
  imports:
    - napari_tomocube_data_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehgus/napari-tomocube-data-viewer
  summary: A plugin to visualize three-dimensional data from Tomocube's microscopy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ehgus
    - goanpeca
    - jaimergp
