{% set name = "napari-tomocube-data-viewer" %}
{% set version = "2024.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dc30fa1d7c2ab8808afcbb8906fea314e99b06ee0a46d1babde911a8865a7d26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools >=42.0.0
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - tcfile ==2024.10.1

test:
  imports:
    - napari_tomocube_data_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-tomocube-data-viewer
  summary: A plugin to visualize three-dimensional data from Tomocube's microscopy
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ehgus/napari-tomocube-data-viewer

extra:
  recipe-maintainers:
    - ehgus
    - goanpeca
    - jaimergp
